package com.selmec.kitpruebas.Models;
// Generated Oct 26, 2014 8:36:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Arranque generated by hbm2java
 */
@Entity
@Table(name="arranque"
    ,catalog="kitpruebas"
)
public class Arranque  implements java.io.Serializable {


     private int id;
     private Prueba prueba;
     private boolean instrumentos;
     private boolean regulador;
     private boolean maestro;
     private boolean multimetro;
     private boolean amperimetro;
     private boolean frecuencimetro;
     private boolean horometro;
     private boolean selector;
     private Boolean fusibles;

    public Arranque() {
    }

	
    public Arranque(Prueba prueba, boolean instrumentos, boolean regulador, boolean maestro, boolean multimetro, boolean amperimetro, boolean frecuencimetro, boolean horometro, boolean selector) {
        this.prueba = prueba;
        this.instrumentos = instrumentos;
        this.regulador = regulador;
        this.maestro = maestro;
        this.multimetro = multimetro;
        this.amperimetro = amperimetro;
        this.frecuencimetro = frecuencimetro;
        this.horometro = horometro;
        this.selector = selector;
    }
    public Arranque(Prueba prueba, boolean instrumentos, boolean regulador, boolean maestro, boolean multimetro, boolean amperimetro, boolean frecuencimetro, boolean horometro, boolean selector, Boolean fusibles) {
       this.prueba = prueba;
       this.instrumentos = instrumentos;
       this.regulador = regulador;
       this.maestro = maestro;
       this.multimetro = multimetro;
       this.amperimetro = amperimetro;
       this.frecuencimetro = frecuencimetro;
       this.horometro = horometro;
       this.selector = selector;
       this.fusibles = fusibles;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="prueba"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }

    
    @Column(name="instrumentos", nullable=false)
    public boolean isInstrumentos() {
        return this.instrumentos;
    }
    
    public void setInstrumentos(boolean instrumentos) {
        this.instrumentos = instrumentos;
    }

    
    @Column(name="regulador", nullable=false)
    public boolean isRegulador() {
        return this.regulador;
    }
    
    public void setRegulador(boolean regulador) {
        this.regulador = regulador;
    }

    
    @Column(name="maestro", nullable=false)
    public boolean isMaestro() {
        return this.maestro;
    }
    
    public void setMaestro(boolean maestro) {
        this.maestro = maestro;
    }

    
    @Column(name="multimetro", nullable=false)
    public boolean isMultimetro() {
        return this.multimetro;
    }
    
    public void setMultimetro(boolean multimetro) {
        this.multimetro = multimetro;
    }

    
    @Column(name="amperimetro", nullable=false)
    public boolean isAmperimetro() {
        return this.amperimetro;
    }
    
    public void setAmperimetro(boolean amperimetro) {
        this.amperimetro = amperimetro;
    }

    
    @Column(name="frecuencimetro", nullable=false)
    public boolean isFrecuencimetro() {
        return this.frecuencimetro;
    }
    
    public void setFrecuencimetro(boolean frecuencimetro) {
        this.frecuencimetro = frecuencimetro;
    }

    
    @Column(name="horometro", nullable=false)
    public boolean isHorometro() {
        return this.horometro;
    }
    
    public void setHorometro(boolean horometro) {
        this.horometro = horometro;
    }

    
    @Column(name="selector", nullable=false)
    public boolean isSelector() {
        return this.selector;
    }
    
    public void setSelector(boolean selector) {
        this.selector = selector;
    }

    
    @Column(name="fusibles")
    public Boolean getFusibles() {
        return this.fusibles;
    }
    
    public void setFusibles(Boolean fusibles) {
        this.fusibles = fusibles;
    }




}


