package com.selmec.kitpruebas.Models;
// Generated Oct 26, 2014 8:36:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cariles generated by hbm2java
 */
@Entity
@Table(name="cariles"
    ,catalog="kitpruebas"
    , uniqueConstraints = {@UniqueConstraint(columnNames="equipo"), @UniqueConstraint(columnNames="NoCarril")} 
)
public class Cariles  implements java.io.Serializable {


     private Integer id;
     private int noCarril;
     private String equipo;
     private Set ensambles = new HashSet(0);
     private String descripcion;

    public Cariles() {
    }

	
    public Cariles(int noCarril, String equipo) {
        this.noCarril = noCarril;
        this.equipo = equipo;
    }
    public Cariles(int noCarril, String equipo, Set ensambles) {
       this.noCarril = noCarril;
       this.equipo = equipo;
       this.ensambles = ensambles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NoCarril", unique=true, nullable=false)
    public int getNoCarril() {
        return this.noCarril;
    }
    
    public void setNoCarril(int noCarril) {
        this.noCarril = noCarril;
    }

    
    @Column(name="equipo", unique=true, nullable=false, length=45)
    public String getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(String equipo) {
        this.equipo = equipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cariles")
    public Set getEnsambles() {
        return this.ensambles;
    }
    
    public void setEnsambles(Set ensambles) {
        this.ensambles = ensambles;
    }

    /**
     * @return the descripcion
     */
    @Column(name="descripcion",  length=100)
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param descripcion the descripcion to set
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


