package com.selmec.kitpruebas.Models;
// Generated Oct 26, 2014 8:36:36 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", catalog = "kitpruebas"
)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Clientes implements java.io.Serializable {

    private int id;
    private String razonSocial;
    private Set ubicacioneses = new HashSet(0);
    private String noCliente;
    private String RFC;

    public Clientes() {
    }

    public Clientes(int id, String razonSocial) {
        this.id = id;
        this.razonSocial = razonSocial;
    }

    public Clientes(int id, String razonSocial, Set ubicacioneses) {
        this.id = id;
        this.razonSocial = razonSocial;
        this.ubicacioneses = ubicacioneses;
    }

    @Id

    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "razonSocial", nullable = false, length = 200)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
    public Set getUbicacioneses() {
        return this.ubicacioneses;
    }

    public void setUbicacioneses(Set ubicacioneses) {
        this.ubicacioneses = ubicacioneses;
    }

    /**
     * @return the noCliente
     */
    @Column(name = "noCliente", length = 20)
    public String getNoCliente() {
        return noCliente;
    }

    /**
     * @param noCliente the noCliente to set
     */
    public void setNoCliente(String noCliente) {
        this.noCliente = noCliente;
    }

    /**
     * @return the RFC
     */
    @Column(name = "RFC", length = 45)
    public String getRFC() {
        return RFC;
    }

    /**
     * @param RFC the RFC to set
     */
    public void setRFC(String RFC) {
        this.RFC = RFC;
    }

}
