package com.selmec.kitpruebas.Models;
// Generated Oct 26, 2014 4:12:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubicaciones generated by hbm2java
 */
@Entity
@Table(name="ubicaciones"
    ,catalog="kitpruebas"
)
public class Ubicaciones  implements java.io.Serializable {


     private int id;
     private Clientes clientes;
     private String poblacion;
     private String estado;
     private String telefono;
     private Set ensambles = new HashSet(0);

    public Ubicaciones() {
    }

	
    public Ubicaciones(int id) {
        this.id = id;
    }
    public Ubicaciones(int id, Clientes clientes, String poblacion, String estado, String telefono, Set ensambles) {
       this.id = id;
       this.clientes = clientes;
       this.poblacion = poblacion;
       this.estado = estado;
       this.telefono = telefono;
       this.ensambles = ensambles;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ClienteId")
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    
    @Column(name="poblacion", length=100)
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    
    @Column(name="estado", length=100)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ubicaciones")
    public Set getEnsambles() {
        return this.ensambles;
    }
    
    public void setEnsambles(Set ensambles) {
        this.ensambles = ensambles;
    }




}


