package com.selmec.kitpruebas.Models;
// Generated Oct 26, 2014 8:36:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Vacio generated by hbm2java
 */
@Entity
@Table(name="vacio"
    ,catalog="kitpruebas"
)
public class Vacio  implements java.io.Serializable {


     private int id;
     private Prueba prueba;
     private boolean proteccion;
     private boolean presion;
     private boolean temperatura;
     private boolean sobrevelocidad;
     private boolean ajustevoltaje;
     private boolean ajustehz;
     private boolean fugas;
     private boolean fugaescape;
     private boolean fases;

    public Vacio() {
    }

    public Vacio(Prueba prueba, boolean proteccion, boolean presion, boolean temperatura, boolean sobrevelocidad, boolean ajustevoltaje, boolean ajustehz, boolean fugas, boolean fugaescape, boolean fases) {
       this.prueba = prueba;
       this.proteccion = proteccion;
       this.presion = presion;
       this.temperatura = temperatura;
       this.sobrevelocidad = sobrevelocidad;
       this.ajustevoltaje = ajustevoltaje;
       this.ajustehz = ajustehz;
       this.fugas = fugas;
       this.fugaescape = fugaescape;
       this.fases = fases;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="prueba"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }

    
    @Column(name="proteccion", nullable=false)
    public boolean isProteccion() {
        return this.proteccion;
    }
    
    public void setProteccion(boolean proteccion) {
        this.proteccion = proteccion;
    }

    
    @Column(name="presion", nullable=false)
    public boolean isPresion() {
        return this.presion;
    }
    
    public void setPresion(boolean presion) {
        this.presion = presion;
    }

    
    @Column(name="temperatura", nullable=false)
    public boolean isTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(boolean temperatura) {
        this.temperatura = temperatura;
    }

    
    @Column(name="sobrevelocidad", nullable=false)
    public boolean isSobrevelocidad() {
        return this.sobrevelocidad;
    }
    
    public void setSobrevelocidad(boolean sobrevelocidad) {
        this.sobrevelocidad = sobrevelocidad;
    }

    
    @Column(name="ajustevoltaje", nullable=false)
    public boolean isAjustevoltaje() {
        return this.ajustevoltaje;
    }
    
    public void setAjustevoltaje(boolean ajustevoltaje) {
        this.ajustevoltaje = ajustevoltaje;
    }

    
    @Column(name="ajustehz", nullable=false)
    public boolean isAjustehz() {
        return this.ajustehz;
    }
    
    public void setAjustehz(boolean ajustehz) {
        this.ajustehz = ajustehz;
    }

    
    @Column(name="fugas", nullable=false)
    public boolean isFugas() {
        return this.fugas;
    }
    
    public void setFugas(boolean fugas) {
        this.fugas = fugas;
    }

    
    @Column(name="fugaescape", nullable=false)
    public boolean isFugaescape() {
        return this.fugaescape;
    }
    
    public void setFugaescape(boolean fugaescape) {
        this.fugaescape = fugaescape;
    }

    
    @Column(name="fases", nullable=false)
    public boolean isFases() {
        return this.fases;
    }
    
    public void setFases(boolean fases) {
        this.fases = fases;
    }




}


